### Hello here we will try to find out to what sheldon would answer to our question

In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_csv("dataset.csv").astype(str)

In [3]:
data.head()

,episode_name,dialogue,person_scene
0,Series 01 Episode 01 – Pilot Episode,A corridor at a sperm bank.,Scene
1,Series 01 Episode 01 – Pilot Episode,So if a photon is directed through a plane wi...,Sheldon
2,Series 01 Episode 01 – Pilot Episode,"Agreed, what’s your point?",Leonard
3,Series 01 Episode 01 – Pilot Episode,"There’s no point, I just think it’s a good id...",Sheldon
4,Series 01 Episode 01 – Pilot Episode,Excuse me?,Leonard

#### Let's work on episode 1 for the time being, and if succeded we can include the rest of the episodes.

##### let's find the index of the rows for episode 1

In [4]:
val = data['episode_name'][0]

In [5]:
index = (data[data['episode_name']==val].index.values)
index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332], dtype=int64)

In [26]:
data

,episode_name,dialogue,person_scene
0,Series 01 Episode 01 – Pilot Episode,A corridor at a sperm bank.,Scene
1,Series 01 Episode 01 – Pilot Episode,So if a photon is directed through a plane wi...,Sheldon
2,Series 01 Episode 01 – Pilot Episode,"Agreed, what’s your point?",Leonard
3,Series 01 Episode 01 – Pilot Episode,"There’s no point, I just think it’s a good id...",Sheldon
4,Series 01 Episode 01 – Pilot Episode,Excuse me?,Leonard
...,...,...,...
54401,Series 10 Episode 24 – The Long Distance Disso...,"And I with you. Question, are you seeking a r...",Sheldon
54402,Series 10 Episode 24 – The Long Distance Disso...,What if I were?,Ramona
54403,Series 10 Episode 24 – The Long Distance Disso...,"Well, that would raise a number of problems. ...",Sheldon
54404,Series 10 Episode 24 – The Long Distance Disso...,Princeton.,Scene
54405,Series 10 Episode 24 – The Long Distance Disso...,"(Knock, knock, knock) Amy. (Knock, knock, kno...",Sheldon

In [7]:
new_df =pd.DataFrame(data).set_index('episode_name')[index[0]:len(index)].copy(deep=True)

In [9]:
new_df = new_df.reset_index(drop=True)
new_df

                                              dialogue person_scene
0                          A corridor at a sperm bank.        Scene
1     So if a photon is directed through a plane wi...      Sheldon
2                           Agreed, what’s your point?      Leonard
3     There’s no point, I just think it’s a good id...      Sheldon
4                                           Excuse me?      Leonard
..                                                 ...          ...
328   Any ideas Raj? (He just looks at her with a w...        Penny
329   Turn left on Lake Street and head up to Color...       Howard
330                              That sounds like fun.        Penny
331   Baby, baby don’t get hooked on me. Uh, baby, ...      (sings)
332   I don’t know what your odds are in the world ...      Sheldon

[333 rows x 2 columns]

In [35]:
index1 = (new_df[new_df['person_scene']!="Sheldon"].index.values)
index1

array([  0,   2,   4,   5,   6,   7,   8,   9,  11,  12,  13,  15,  17,
        19,  21,  23,  25,  27,  29,  30,  32,  34,  36,  38,  40,  42,
        44,  45,  47,  49,  50,  51,  52,  53,  54,  55,  56,  58,  59,
        60,  61,  62,  64,  65,  67,  68,  70,  72,  74,  76,  78,  80,
        82,  83,  85,  86,  87,  89,  90,  91,  92,  93,  95,  96,  97,
        98,  99, 101, 103, 105, 106, 107, 109, 111, 113, 115, 117, 119,
       121, 123, 125, 127, 129, 131, 133, 135, 137, 138, 139, 140, 142,
       143, 144, 146, 147, 148, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 162, 163, 164, 166, 168, 169, 170, 171, 173, 175,
       177, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 197, 198,
       199, 200, 201, 202, 203, 204, 205, 207, 208, 209, 210, 211, 212,
       213, 214, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226,
       227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 239, 241,
       243, 245, 247, 249, 251, 253, 255, 256, 257, 258, 259, 260, 261,
       262, 263, 264, 266, 267, 269, 271, 274, 276, 277, 278, 280, 281,
       283, 284, 286, 288, 290, 292, 293, 295, 297, 299, 301, 302, 303,
       304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 315, 316, 318,
       320, 321, 322, 324, 326, 328, 329, 330, 331], dtype=int64)

##### now for version 1.0 we will have data set of dialogues only of sheldon

In [42]:
df = new_df.drop(index1)
df

                                              dialogue person_scene
1     So if a photon is directed through a plane wi...      Sheldon
3     There’s no point, I just think it’s a good id...      Sheldon
10                          I think this is the place.      Sheldon
14               Leonard, I don’t think I can do this.      Sheldon
16    No. We are committing genetic fraud. There’s ...      Sheldon
..                                                 ...          ...
319                          Not to mention imaginary.      Sheldon
323   We can’t have Thai food, we had Indian for lu...      Sheldon
325                 They’re both curry based cuisines.      Sheldon
327   They would be gastronomically redundant. I ca...      Sheldon
332   I don’t know what your odds are in the world ...      Sheldon

[103 rows x 2 columns]

In [44]:
df = df.reset_index(drop=True)

In [46]:
import random
df['dialogue'][random.randint(0,102)]

' Yeah. '